---
name: Luigui
surname: Gallardo-Becerra
date: "`r format(Sys.time(), '%B, %Y')`"
position: Data Scientist | Bioinformatician
address: San Diego, California (USA)
#phone: +47 4125 91 17
email: luiguimichelgallardo@gmail.com
website: file:///Users/luigui/Documents/web_page/index.html
github: LuiguiGallardo
linkedin: luiguigallardo
output: vitae::moderncv

header-includes:
  - \usepackage{colortbl}
  - \definecolor{darktext}{HTML}{414141}
  - \definecolor{text}{HTML}{333333}
  - \definecolor{graytext}{HTML}{5D5D5D}
  - \definecolor{lighttext}{HTML}{999999}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(vitae)
```


\vspace{1.25cm} \rightline{\textcolor{graytext}{\today}}

\vspace{-0.5cm}  **TARDIS**    \
\textcolor{graytext}{The Stone Age}     \
\textcolor{graytext}{London}             

\vspace{0.25cm}\textbf{\underline{An Unearthly Child}}  
\vspace{0.15cm} \textcolor{graytext}{Dear Dr. Who,}

\vspace*{0.25cm}

I am writing to apply for this Data Science position because I believe my educational background and working experience make me a qualified candidate for this position. I am a Ph.D. candidate with with the purpose of integrating my skills and knowledge to this industry.
\vspace*{0.25cm}

I have studied the major of Bioinformatics, that is the application of Computer and Data Sciences to biological data, since I finished my Bachelor's degree. After getting my bachelor's degree, I won a scholarship to continue with my M.Sc. and Ph.D. at UNAM, which is the top university in Mexico and worldwide recognized. As a graduate student researcher, I participated in different projects using modern genomic technologies and Data Science applied to biological data to obtain novel information.
\vspace*{0.25cm}

Having studied the job description, I am confident that I have the skills, qualities, and qualifications needed to excel in the role. Additionally, I consider myself a fast learner and could quickly adapt to your company. If I don't know something, I always look for a way to learn it. I possess excellent problem-solving capabilities, and I can manage a significant workload or several projects from different areas without losing track of each of them. For example, I participated in several research projects, managed the server, the GitHub account, and the scripts for those projects. Also, I am familiar with working remotely, so it wouldn't be such a difficult transition for me.
\vspace*{0.25cm}

I attached my CV and my personal webpage, where you can see my portfolio and publications.

Thanks a lot for your attention, and I look forward to being in touch with you in the future.

Best regards,

\vspace*{0.25cm} **Luigui Gallardo-Becerra**
